EXEC AddCountry @FullName = N'Afghanistan', @ShortName = N'Afghanistan';
EXEC AddCountry @FullName = N'Albania', @ShortName = N'Albania';
EXEC AddCountry @FullName = N'Algeria', @ShortName = N'Algeria';
EXEC AddCountry @FullName = N'American Samoa', @ShortName = N'American Samoa';
EXEC AddCountry @FullName = N'Andorra', @ShortName = N'Andorra';
EXEC AddCountry @FullName = N'Angola', @ShortName = N'Angola';
EXEC AddCountry @FullName = N'Antigua and Barbuda', @ShortName = N'Antigua and Barbuda';
EXEC AddCountry @FullName = N'Argentina', @ShortName = N'Argentina';
EXEC AddCountry @FullName = N'Armenia', @ShortName = N'Armenia';
EXEC AddCountry @FullName = N'Aruba', @ShortName = N'Aruba';
EXEC AddCountry @FullName = N'Australia', @ShortName = N'Australia';
EXEC AddCountry @FullName = N'Austria', @ShortName = N'Austria';
EXEC AddCountry @FullName = N'Azerbaijan', @ShortName = N'Azerbaijan';
EXEC AddCountry @FullName = N'Bahamas', @ShortName = N'Bahamas';
EXEC AddCountry @FullName = N'Bahrain', @ShortName = N'Bahrain';
EXEC AddCountry @FullName = N'Bangladesh', @ShortName = N'Bangladesh';
EXEC AddCountry @FullName = N'Barbados', @ShortName = N'Barbados';
EXEC AddCountry @FullName = N'Belarus', @ShortName = N'Belarus';
EXEC AddCountry @FullName = N'Belgium', @ShortName = N'Belgium';
EXEC AddCountry @FullName = N'Belize', @ShortName = N'Belize';
EXEC AddCountry @FullName = N'Benin', @ShortName = N'Benin';
EXEC AddCountry @FullName = N'Bermuda', @ShortName = N'Bermuda';
EXEC AddCountry @FullName = N'Bhutan', @ShortName = N'Bhutan';
EXEC AddCountry @FullName = N'Bolivia', @ShortName = N'Bolivia';
EXEC AddCountry @FullName = N'Bosnia and Herzegovina', @ShortName = N'Bosnia and Herzegovina';
EXEC AddCountry @FullName = N'Botswana', @ShortName = N'Botswana';
EXEC AddCountry @FullName = N'Brazil', @ShortName = N'Brazil';
EXEC AddCountry @FullName = N'British Virgin Islands', @ShortName = N'British Virgin Islands';
EXEC AddCountry @FullName = N'Brunei Darussalam', @ShortName = N'Brunei Darussalam';
EXEC AddCountry @FullName = N'Bulgaria', @ShortName = N'Bulgaria';
EXEC AddCountry @FullName = N'Burkina Faso', @ShortName = N'Burkina Faso';
EXEC AddCountry @FullName = N'Burundi', @ShortName = N'Burundi';
EXEC AddCountry @FullName = N'Cabo Verde', @ShortName = N'Cabo Verde';
EXEC AddCountry @FullName = N'Cambodia', @ShortName = N'Cambodia';
EXEC AddCountry @FullName = N'Cameroon', @ShortName = N'Cameroon';
EXEC AddCountry @FullName = N'Canada', @ShortName = N'Canada';
EXEC AddCountry @FullName = N'Cayman Islands', @ShortName = N'Cayman Islands';
EXEC AddCountry @FullName = N'Central African Republic', @ShortName = N'Central African Republic';
EXEC AddCountry @FullName = N'Chad', @ShortName = N'Chad';
EXEC AddCountry @FullName = N'Channel Islands', @ShortName = N'Channel Islands';
EXEC AddCountry @FullName = N'Chile', @ShortName = N'Chile';
EXEC AddCountry @FullName = N'China', @ShortName = N'China';
EXEC AddCountry @FullName = N'Colombia', @ShortName = N'Colombia';
EXEC AddCountry @FullName = N'Comoros', @ShortName = N'Comoros';
EXEC AddCountry @FullName = N'Congo', @ShortName = N'Congo';
EXEC AddCountry @FullName = N'Costa Rica', @ShortName = N'Costa Rica';
EXEC AddCountry @FullName = N'Cote d''Ivoire', @ShortName = N'Cote d''Ivoire';
EXEC AddCountry @FullName = N'Croatia', @ShortName = N'Croatia';
EXEC AddCountry @FullName = N'Cuba', @ShortName = N'Cuba';
EXEC AddCountry @FullName = N'Curacao', @ShortName = N'Curacao';
EXEC AddCountry @FullName = N'Cyprus', @ShortName = N'Cyprus';
EXEC AddCountry @FullName = N'Czechia', @ShortName = N'Czechia';
EXEC AddCountry @FullName = N'Denmark', @ShortName = N'Denmark';
EXEC AddCountry @FullName = N'Djibouti', @ShortName = N'Djibouti';
EXEC AddCountry @FullName = N'Dominica', @ShortName = N'Dominica';
EXEC AddCountry @FullName = N'Dominican Republic', @ShortName = N'Dominican Republic';
EXEC AddCountry @FullName = N'Ecuador', @ShortName = N'Ecuador';
EXEC AddCountry @FullName = N'Egypt', @ShortName = N'Egypt';
EXEC AddCountry @FullName = N'El Salvador', @ShortName = N'El Salvador';
EXEC AddCountry @FullName = N'Equatorial Guinea', @ShortName = N'Equatorial Guinea';
EXEC AddCountry @FullName = N'Eritrea', @ShortName = N'Eritrea';
EXEC AddCountry @FullName = N'Estonia', @ShortName = N'Estonia';
EXEC AddCountry @FullName = N'Eswatini', @ShortName = N'Eswatini';
EXEC AddCountry @FullName = N'Ethiopia', @ShortName = N'Ethiopia';
EXEC AddCountry @FullName = N'Faroe Islands', @ShortName = N'Faroe Islands';
EXEC AddCountry @FullName = N'Fiji', @ShortName = N'Fiji';
EXEC AddCountry @FullName = N'Finland', @ShortName = N'Finland';
EXEC AddCountry @FullName = N'France', @ShortName = N'France';
EXEC AddCountry @FullName = N'French Polynesia', @ShortName = N'French Polynesia';
EXEC AddCountry @FullName = N'Gabon', @ShortName = N'Gabon';
EXEC AddCountry @FullName = N'Gambia', @ShortName = N'Gambia';
EXEC AddCountry @FullName = N'Georgia', @ShortName = N'Georgia';
EXEC AddCountry @FullName = N'Germany', @ShortName = N'Germany';
EXEC AddCountry @FullName = N'Ghana', @ShortName = N'Ghana';
EXEC AddCountry @FullName = N'Gibraltar', @ShortName = N'Gibraltar';
EXEC AddCountry @FullName = N'Great Britain', @ShortName = N'Great Britain';
EXEC AddCountry @FullName = N'Greece', @ShortName = N'Greece';
EXEC AddCountry @FullName = N'Greenland', @ShortName = N'Greenland';
EXEC AddCountry @FullName = N'Grenada', @ShortName = N'Grenada';
EXEC AddCountry @FullName = N'Guam', @ShortName = N'Guam';
EXEC AddCountry @FullName = N'Guatemala', @ShortName = N'Guatemala';
EXEC AddCountry @FullName = N'Guinea', @ShortName = N'Guinea';
EXEC AddCountry @FullName = N'Guinea-Bissau', @ShortName = N'Guinea-Bissau';
EXEC AddCountry @FullName = N'Guyana', @ShortName = N'Guyana';
EXEC AddCountry @FullName = N'Haiti', @ShortName = N'Haiti';
EXEC AddCountry @FullName = N'Honduras', @ShortName = N'Honduras';
EXEC AddCountry @FullName = N'Hong Kong', @ShortName = N'Hong Kong';
EXEC AddCountry @FullName = N'Hungary', @ShortName = N'Hungary';
EXEC AddCountry @FullName = N'Iceland', @ShortName = N'Iceland';
EXEC AddCountry @FullName = N'India', @ShortName = N'India';
EXEC AddCountry @FullName = N'Indonesia', @ShortName = N'Indonesia';
EXEC AddCountry @FullName = N'Iran', @ShortName = N'Iran';
EXEC AddCountry @FullName = N'Iraq', @ShortName = N'Iraq';
EXEC AddCountry @FullName = N'Ireland', @ShortName = N'Ireland';
EXEC AddCountry @FullName = N'Isle of Man', @ShortName = N'Isle of Man';
EXEC AddCountry @FullName = N'Israel', @ShortName = N'Israel';
EXEC AddCountry @FullName = N'Italy', @ShortName = N'Italy';
EXEC AddCountry @FullName = N'Jamaica', @ShortName = N'Jamaica';
EXEC AddCountry @FullName = N'Japan', @ShortName = N'Japan';
EXEC AddCountry @FullName = N'Jordan', @ShortName = N'Jordan';
EXEC AddCountry @FullName = N'Kazakhstan', @ShortName = N'Kazakhstan';
EXEC AddCountry @FullName = N'Kenya', @ShortName = N'Kenya';
EXEC AddCountry @FullName = N'Kiribati', @ShortName = N'Kiribati';
EXEC AddCountry @FullName = N'North Korea', @ShortName = N'North Korea';
EXEC AddCountry @FullName = N'South Korea', @ShortName = N'South Korea';
EXEC AddCountry @FullName = N'Kosovo', @ShortName = N'Kosovo';
EXEC AddCountry @FullName = N'Kuwait', @ShortName = N'Kuwait';
EXEC AddCountry @FullName = N'Kyrgyz Republic', @ShortName = N'Kyrgyz Republic';
EXEC AddCountry @FullName = N'Lao PDR', @ShortName = N'Lao PDR';
EXEC AddCountry @FullName = N'Latvia', @ShortName = N'Latvia';
EXEC AddCountry @FullName = N'Lebanon', @ShortName = N'Lebanon';
EXEC AddCountry @FullName = N'Lesotho', @ShortName = N'Lesotho';
EXEC AddCountry @FullName = N'Liberia', @ShortName = N'Liberia';
EXEC AddCountry @FullName = N'Libya', @ShortName = N'Libya';
EXEC AddCountry @FullName = N'Liechtenstein', @ShortName = N'Liechtenstein';
EXEC AddCountry @FullName = N'Lithuania', @ShortName = N'Lithuania';
EXEC AddCountry @FullName = N'Luxembourg', @ShortName = N'Luxembourg';
EXEC AddCountry @FullName = N'Macao', @ShortName = N'Macao';
EXEC AddCountry @FullName = N'Madagascar', @ShortName = N'Madagascar';
EXEC AddCountry @FullName = N'Malawi', @ShortName = N'Malawi';
EXEC AddCountry @FullName = N'Malaysia', @ShortName = N'Malaysia';
EXEC AddCountry @FullName = N'Maldives', @ShortName = N'Maldives';
EXEC AddCountry @FullName = N'Mali', @ShortName = N'Mali';
EXEC AddCountry @FullName = N'Malta', @ShortName = N'Malta';
EXEC AddCountry @FullName = N'Marshall Islands', @ShortName = N'Marshall Islands';
EXEC AddCountry @FullName = N'Mauritania', @ShortName = N'Mauritania';
EXEC AddCountry @FullName = N'Mauritius', @ShortName = N'Mauritius';
EXEC AddCountry @FullName = N'Mexico', @ShortName = N'Mexico';
EXEC AddCountry @FullName = N'Micronesia', @ShortName = N'Micronesia';
EXEC AddCountry @FullName = N'Moldova', @ShortName = N'Moldova';
EXEC AddCountry @FullName = N'Monaco', @ShortName = N'Monaco';
EXEC AddCountry @FullName = N'Mongolia', @ShortName = N'Mongolia';
EXEC AddCountry @FullName = N'Montenegro', @ShortName = N'Montenegro';
EXEC AddCountry @FullName = N'Morocco', @ShortName = N'Morocco';
EXEC AddCountry @FullName = N'Mozambique', @ShortName = N'Mozambique';
EXEC AddCountry @FullName = N'Myanmar', @ShortName = N'Myanmar';
EXEC AddCountry @FullName = N'Namibia', @ShortName = N'Namibia';
EXEC AddCountry @FullName = N'Nauru', @ShortName = N'Nauru';
EXEC AddCountry @FullName = N'Nepal', @ShortName = N'Nepal';
EXEC AddCountry @FullName = N'Netherlands', @ShortName = N'Netherlands';
EXEC AddCountry @FullName = N'New Caledonia', @ShortName = N'New Caledonia';
EXEC AddCountry @FullName = N'New Zealand', @ShortName = N'New Zealand';
EXEC AddCountry @FullName = N'Nicaragua', @ShortName = N'Nicaragua';
EXEC AddCountry @FullName = N'Niger', @ShortName = N'Niger';
EXEC AddCountry @FullName = N'Nigeria', @ShortName = N'Nigeria';
EXEC AddCountry @FullName = N'North Macedonia', @ShortName = N'North Macedonia';
EXEC AddCountry @FullName = N'Northern Mariana Islands', @ShortName = N'Northern Mariana Islands';
EXEC AddCountry @FullName = N'Norway', @ShortName = N'Norway';
EXEC AddCountry @FullName = N'Oman', @ShortName = N'Oman';
EXEC AddCountry @FullName = N'Pakistan', @ShortName = N'Pakistan';
EXEC AddCountry @FullName = N'Palau', @ShortName = N'Palau';
EXEC AddCountry @FullName = N'Panama', @ShortName = N'Panama';
EXEC AddCountry @FullName = N'Papua New Guinea', @ShortName = N'Papua New Guinea';
EXEC AddCountry @FullName = N'Paraguay', @ShortName = N'Paraguay';
EXEC AddCountry @FullName = N'Peru', @ShortName = N'Peru';
EXEC AddCountry @FullName = N'Philippines', @ShortName = N'Philippines';
EXEC AddCountry @FullName = N'Poland', @ShortName = N'Poland';
EXEC AddCountry @FullName = N'Portugal', @ShortName = N'Portugal';
EXEC AddCountry @FullName = N'Puerto Rico', @ShortName = N'Puerto Rico';
EXEC AddCountry @FullName = N'Qatar', @ShortName = N'Qatar';
EXEC AddCountry @FullName = N'Romania', @ShortName = N'Romania';
EXEC AddCountry @FullName = N'Russian Federation', @ShortName = N'Russia';
EXEC AddCountry @FullName = N'Rwanda', @ShortName = N'Rwanda';
EXEC AddCountry @FullName = N'Samoa', @ShortName = N'Samoa';
EXEC AddCountry @FullName = N'San Marino', @ShortName = N'San Marino';
EXEC AddCountry @FullName = N'Sao Tome and Principe', @ShortName = N'Sao Tome and Principe';
EXEC AddCountry @FullName = N'Saudi Arabia', @ShortName = N'Saudi Arabia';
EXEC AddCountry @FullName = N'Senegal', @ShortName = N'Senegal';
EXEC AddCountry @FullName = N'Serbia', @ShortName = N'Serbia';
EXEC AddCountry @FullName = N'Seychelles', @ShortName = N'Seychelles';
EXEC AddCountry @FullName = N'Sierra Leone', @ShortName = N'Sierra Leone';
EXEC AddCountry @FullName = N'Singapore', @ShortName = N'Singapore';
EXEC AddCountry @FullName = N'Sint Maarten', @ShortName = N'Sint Maarten';
EXEC AddCountry @FullName = N'Slovak Republic', @ShortName = N'Slovak Republic';
EXEC AddCountry @FullName = N'Slovenia', @ShortName = N'Slovenia';
EXEC AddCountry @FullName = N'Solomon Islands', @ShortName = N'Solomon Islands';
EXEC AddCountry @FullName = N'Somalia', @ShortName = N'Somalia';
EXEC AddCountry @FullName = N'South Africa', @ShortName = N'South Africa';
EXEC AddCountry @FullName = N'South Sudan', @ShortName = N'South Sudan';
EXEC AddCountry @FullName = N'Spain', @ShortName = N'Spain';
EXEC AddCountry @FullName = N'Sri Lanka', @ShortName = N'Sri Lanka';
EXEC AddCountry @FullName = N'St. Kitts and Nevis', @ShortName = N'St. Kitts and Nevis';
EXEC AddCountry @FullName = N'St. Lucia', @ShortName = N'St. Lucia';
EXEC AddCountry @FullName = N'St. Martin', @ShortName = N'St. Martin';
EXEC AddCountry @FullName = N'St. Vincent and the Grenadines', @ShortName = N'St. Vincent and the Grenadines';
EXEC AddCountry @FullName = N'Sudan', @ShortName = N'Sudan';
EXEC AddCountry @FullName = N'Suriname', @ShortName = N'Suriname';
EXEC AddCountry @FullName = N'Sweden', @ShortName = N'Sweden';
EXEC AddCountry @FullName = N'Switzerland', @ShortName = N'Switzerland';
EXEC AddCountry @FullName = N'Syrian Arab Republic', @ShortName = N'Syrian Arab Republic';
EXEC AddCountry @FullName = N'Tajikistan', @ShortName = N'Tajikistan';
EXEC AddCountry @FullName = N'Tanzania', @ShortName = N'Tanzania';
EXEC AddCountry @FullName = N'Thailand', @ShortName = N'Thailand';
EXEC AddCountry @FullName = N'Timor-Leste', @ShortName = N'Timor-Leste';
EXEC AddCountry @FullName = N'Togo', @ShortName = N'Togo';
EXEC AddCountry @FullName = N'Tonga', @ShortName = N'Tonga';
EXEC AddCountry @FullName = N'Trinidad and Tobago', @ShortName = N'Trinidad and Tobago';
EXEC AddCountry @FullName = N'Tunisia', @ShortName = N'Tunisia';
EXEC AddCountry @FullName = N'Turkey', @ShortName = N'Turkey';
EXEC AddCountry @FullName = N'Turkmenistan', @ShortName = N'Turkmenistan';
EXEC AddCountry @FullName = N'Turks and Caicos Islands', @ShortName = N'Turks and Caicos Islands';
EXEC AddCountry @FullName = N'Tuvalu', @ShortName = N'Tuvalu';
EXEC AddCountry @FullName = N'Uganda', @ShortName = N'Uganda';
EXEC AddCountry @FullName = N'Ukraine', @ShortName = N'Ukraine';
EXEC AddCountry @FullName = N'United Arab Emirates', @ShortName = N'U.A.E.';
EXEC AddCountry @FullName = N'United States', @ShortName = N'USA';
EXEC AddCountry @FullName = N'Uruguay', @ShortName = N'Uruguay';
EXEC AddCountry @FullName = N'Uzbekistan', @ShortName = N'Uzbekistan';
EXEC AddCountry @FullName = N'Vanuatu', @ShortName = N'Vanuatu';
EXEC AddCountry @FullName = N'Venezuela', @ShortName = N'Venezuela';
EXEC AddCountry @FullName = N'Vietnam', @ShortName = N'Vietnam';
EXEC AddCountry @FullName = N'Virgin Islands', @ShortName = N'Virgin Islands';
EXEC AddCountry @FullName = N'West Bank and Gaza', @ShortName = N'West Bank and Gaza';
EXEC AddCountry @FullName = N'Yemen', @ShortName = N'Yemen';
EXEC AddCountry @FullName = N'Zambia', @ShortName = N'Zambia';
EXEC AddCountry @FullName = N'Zimbabwe', @ShortName = N'Zimbabwe';