EXEC AddTrack @CountryID = 15, @FullName = N'Bahrain International Circuit', @ShortName = N'Bahrain';
EXEC AddTrack @CountryID = 97, @FullName = N'Autodromo Internazionale Enzo e Dino Ferrari', @ShortName = N'Imola';
EXEC AddTrack @CountryID = 157, @FullName = N'Autodromo de Algarve', @ShortName = N'Algarve';
EXEC AddTrack @CountryID = 179, @FullName = N'Circuit de Catalunya', @ShortName = N'Catalunya';
EXEC AddTrack @CountryID = 130, @FullName = N'Circuit de Monaco', @ShortName = N'Monaco';
EXEC AddTrack @CountryID = 13, @FullName = N'Baku City Circuit', @ShortName = N'Baku';
EXEC AddTrack @CountryID = 68, @FullName = N'Circuit Paul Ricard', @ShortName = N'Paul Ricard';
EXEC AddTrack @CountryID = 12, @FullName = N'Red Bull Ring', @ShortName = N'Red Bull Ring';
EXEC AddTrack @CountryID = 76, @FullName = N'Silverstone Circuit', @ShortName = N'Silverstone';
EXEC AddTrack @CountryID = 88, @FullName = N'Hungaroring', @ShortName = N'Hungaroring';
EXEC AddTrack @CountryID = 19, @FullName = N'Circuit de Spa-Francorchamps', @ShortName = N'Spa';
EXEC AddTrack @CountryID = 139, @FullName = N'Circuit Zandvoort', @ShortName = N'Zandvoort';
EXEC AddTrack @CountryID = 97, @FullName = N'Autodromo Nazionale di Monza', @ShortName = N'Monza';
EXEC AddTrack @CountryID = 161, @FullName = N'Sochi Autodrom', @ShortName = N'Sochi Autodrom';
EXEC AddTrack @CountryID = 198, @FullName = N'Intercity Istanbul Park', @ShortName = N'Istanbul Park';
EXEC AddTrack @CountryID = 205, @FullName = N'Circuit of the Americas', @ShortName = N'COTA';
EXEC AddTrack @CountryID = 127, @FullName = N'Autodromo Hermanos Rodriguez', @ShortName = N'Hermanos Rodriguez';
EXEC AddTrack @CountryID = 27, @FullName = N'Autodromo Jose Carlos Pace', @ShortName = N'Interlagos';
EXEC AddTrack @CountryID = 159, @FullName = N'Losail International Circuit', @ShortName = N'Losail';
EXEC AddTrack @CountryID = 166, @FullName = N'Jeddah Corniche Circuit', @ShortName = N'Jeddah';
EXEC AddTrack @CountryID = 204, @FullName = N'Yas Marina Circuit', @ShortName = N'Yas Marina';
EXEC AddTrack @CountryID = 99, @FullName = N'Suzuka International Racing Course', @ShortName = N'Suzuka';