EXEC AddConfig @Description = N'F121 Ferrari TT Suzuka', @GameID = 1, @TrackID = 22, @CarID = 3, @WeatherID = 1, @TyreID = 1, @SetupID = 5;
EXEC AddConfig @Description = N'F121 Ferrari TT Wet Suzuka', @GameID = 1, @TrackID = 22, @CarID = 3, @WeatherID = 2, @TyreID = 5, @SetupID = 5;
EXEC AddConfig @Description = N'F121 Ferrari TT Monza', @GameID = 1, @TrackID = 13, @CarID = 3, @WeatherID = 1, @TyreID = 1, @SetupID = 5;
EXEC AddConfig @Description = N'F121 Ferrari TT Wet Monza', @GameID = 1, @TrackID = 13, @CarID = 3, @WeatherID = 2, @TyreID = 5, @SetupID = 5;
EXEC AddConfig @Description = N'F121 Ferrari TT Red Bull Ring', @GameID = 1, @TrackID = 8, @CarID = 3, @WeatherID = 1, @TyreID = 1, @SetupID = 5;
EXEC AddConfig @Description = N'F121 Ferrari TT Hermanos Rodriguez', @GameID = 1, @TrackID = 17, @CarID = 3, @WeatherID = 1, @TyreID = 1, @SetupID = 5;
EXEC AddConfig @Description = N'F121 Ferrari TT Custom Hermanos Rodriguez', @GameID = 1, @TrackID = 17, @CarID = 3, @WeatherID = 1, @TyreID = 1, @SetupID = 2;
EXEC AddConfig @Description = N'F121 Ferrari TT Custom Zandvoort', @GameID = 1, @TrackID = 12, @CarID = 3, @WeatherID = 1, @TyreID = 1, @SetupID = 2;
EXEC AddConfig @Description = N'F121 Mercedes TT Custom Hermanos Rodriguez', @GameID = 1, @TrackID = 17, @CarID = 1, @WeatherID = 1, @TyreID = 1, @SetupID = 2;
EXEC AddConfig @Description = N'F121 Ferrari TT Custom Monza', @GameID = 1, @TrackID = 13, @CarID = 3, @WeatherID = 1, @TyreID = 1, @SetupID = 2;