EXEC AddCar @FullName = N'Mercedes-AMG F1 W12 E Performance', @ShortName = N'Mercedes W12';
EXEC AddCar @FullName = N'Williams FW43B', @ShortName = N'Williams FW43B';
EXEC AddCar @FullName = N'Ferrari SF21', @ShortName = N'Ferrari SF21';
EXEC AddCar @FullName = N'Aston Martin AMR21', @ShortName = N'Aston Martin AMR21';
EXEC AddCar @FullName = N'Alpine A521', @ShortName = N'Alpine A521';
EXEC AddCar @FullName = N'McLaren MCL35M', @ShortName = N'McLaren MCL35M';
EXEC AddCar @FullName = N'Red Bull Racing RB16B', @ShortName = N'Red Bull RB16B';
EXEC AddCar @FullName = N'Alfa Romeo Racing C41', @ShortName = N'Alfa Romeo C41';
EXEC AddCar @FullName = N'AlphaTauri AT02', @ShortName = N'AlphaTauri AT02';
EXEC AddCar @FullName = N'Haas VF-21', @ShortName = N'Haas VF-21';
EXEC AddCar @FullName = N'Dallara F2 2018', @ShortName = N'Dallara F2 2018';
EXEC AddCar @FullName = N'Racing Point RP20', @ShortName = N'Racing Point RP20';
EXEC AddCar @FullName = N'Mercedes-AMG F1 W11 EQ Performance', @ShortName = N'Mercedes W11';
EXEC AddCar @FullName = N'Ferrari SF1000', @ShortName = N'Ferrari SF1000';
EXEC AddCar @FullName = N'Red Bull Racing RB16', @ShortName = N'Red Bull RB16';
EXEC AddCar @FullName = N'Williams FW43', @ShortName = N'Williams FW43';
EXEC AddCar @FullName = N'Renault R.S.20', @ShortName = N'Renault R.S.20';
EXEC AddCar @FullName = N'AlphaTauri AT01', @ShortName = N'AlphaTauri AT01';
EXEC AddCar @FullName = N'Haas VF-20', @ShortName = N'Haas VF-20';
EXEC AddCar @FullName = N'McLaren MCL35', @ShortName = N'McLaren MCL35';
EXEC AddCar @FullName = N'Alfa Romeo Racing C39', @ShortName = N'Alfa Romeo C39';