EXEC AddCountry @FullName = N'Afghanistan', @ShortName = N'Afghanistan', @Alpha2Code = N'AF';
EXEC AddCountry @FullName = N'Albania', @ShortName = N'Albania', @Alpha2Code = N'AL';
EXEC AddCountry @FullName = N'Algeria', @ShortName = N'Algeria', @Alpha2Code = N'DZ';
EXEC AddCountry @FullName = N'American Samoa', @ShortName = N'American Samoa', @Alpha2Code = N'AS';
EXEC AddCountry @FullName = N'Andorra', @ShortName = N'Andorra', @Alpha2Code = N'AD';
EXEC AddCountry @FullName = N'Angola', @ShortName = N'Angola', @Alpha2Code = N'AO';
EXEC AddCountry @FullName = N'Antigua and Barbuda', @ShortName = N'Antigua and Barbuda', @Alpha2Code = N'AG';
EXEC AddCountry @FullName = N'Argentina', @ShortName = N'Argentina', @Alpha2Code = N'AR';
EXEC AddCountry @FullName = N'Armenia', @ShortName = N'Armenia', @Alpha2Code = N'AM';
EXEC AddCountry @FullName = N'Aruba', @ShortName = N'Aruba', @Alpha2Code = N'AW';
EXEC AddCountry @FullName = N'Australia', @ShortName = N'Australia', @Alpha2Code = N'AU';
EXEC AddCountry @FullName = N'Austria', @ShortName = N'Austria', @Alpha2Code = N'AT';
EXEC AddCountry @FullName = N'Azerbaijan', @ShortName = N'Azerbaijan', @Alpha2Code = N'AZ';
EXEC AddCountry @FullName = N'Bahamas', @ShortName = N'Bahamas', @Alpha2Code = N'BS';
EXEC AddCountry @FullName = N'Bahrain', @ShortName = N'Bahrain', @Alpha2Code = N'BH';
EXEC AddCountry @FullName = N'Bangladesh', @ShortName = N'Bangladesh', @Alpha2Code = N'BD';
EXEC AddCountry @FullName = N'Barbados', @ShortName = N'Barbados', @Alpha2Code = N'BB';
EXEC AddCountry @FullName = N'Belarus', @ShortName = N'Belarus', @Alpha2Code = N'BY';
EXEC AddCountry @FullName = N'Belgium', @ShortName = N'Belgium', @Alpha2Code = N'BE';
EXEC AddCountry @FullName = N'Belize', @ShortName = N'Belize', @Alpha2Code = N'BZ';
EXEC AddCountry @FullName = N'Benin', @ShortName = N'Benin', @Alpha2Code = N'BJ';
EXEC AddCountry @FullName = N'Bermuda', @ShortName = N'Bermuda', @Alpha2Code = N'BM';
EXEC AddCountry @FullName = N'Bhutan', @ShortName = N'Bhutan', @Alpha2Code = N'BT';
EXEC AddCountry @FullName = N'Bolivia', @ShortName = N'Bolivia', @Alpha2Code = N'BO';
EXEC AddCountry @FullName = N'Bosnia and Herzegovina', @ShortName = N'Bosnia and Herzegovina', @Alpha2Code = N'BA';
EXEC AddCountry @FullName = N'Botswana', @ShortName = N'Botswana', @Alpha2Code = N'BW';
EXEC AddCountry @FullName = N'Brazil', @ShortName = N'Brazil', @Alpha2Code = N'BR';
EXEC AddCountry @FullName = N'British Virgin Islands', @ShortName = N'British Virgin Islands', @Alpha2Code = N'VG';
EXEC AddCountry @FullName = N'Brunei Darussalam', @ShortName = N'Brunei Darussalam', @Alpha2Code = N'BN';
EXEC AddCountry @FullName = N'Bulgaria', @ShortName = N'Bulgaria', @Alpha2Code = N'BG';
EXEC AddCountry @FullName = N'Burkina Faso', @ShortName = N'Burkina Faso', @Alpha2Code = N'BF';
EXEC AddCountry @FullName = N'Burundi', @ShortName = N'Burundi', @Alpha2Code = N'BI';
EXEC AddCountry @FullName = N'Cabo Verde', @ShortName = N'Cabo Verde', @Alpha2Code = N'CV';
EXEC AddCountry @FullName = N'Cambodia', @ShortName = N'Cambodia', @Alpha2Code = N'KH';
EXEC AddCountry @FullName = N'Cameroon', @ShortName = N'Cameroon', @Alpha2Code = N'CM';
EXEC AddCountry @FullName = N'Canada', @ShortName = N'Canada', @Alpha2Code = N'CA';
EXEC AddCountry @FullName = N'Cayman Islands', @ShortName = N'Cayman Islands', @Alpha2Code = N'KY';
EXEC AddCountry @FullName = N'Central African Republic', @ShortName = N'Central African Republic', @Alpha2Code = N'CF';
EXEC AddCountry @FullName = N'Chad', @ShortName = N'Chad', @Alpha2Code = N'TD';
EXEC AddCountry @FullName = N'Chile', @ShortName = N'Chile', @Alpha2Code = N'CL';
EXEC AddCountry @FullName = N'China', @ShortName = N'China', @Alpha2Code = N'CN';
EXEC AddCountry @FullName = N'Colombia', @ShortName = N'Colombia', @Alpha2Code = N'CO';
EXEC AddCountry @FullName = N'Comoros', @ShortName = N'Comoros', @Alpha2Code = N'KM';
EXEC AddCountry @FullName = N'Congo', @ShortName = N'Congo', @Alpha2Code = N'CG';
EXEC AddCountry @FullName = N'Costa Rica', @ShortName = N'Costa Rica', @Alpha2Code = N'CR';
EXEC AddCountry @FullName = N'Cote d''Ivoire', @ShortName = N'Cote d''Ivoire', @Alpha2Code = N'CI';
EXEC AddCountry @FullName = N'Croatia', @ShortName = N'Croatia', @Alpha2Code = N'HR';
EXEC AddCountry @FullName = N'Cuba', @ShortName = N'Cuba', @Alpha2Code = N'CU';
EXEC AddCountry @FullName = N'Curacao', @ShortName = N'Curacao', @Alpha2Code = N'CW';
EXEC AddCountry @FullName = N'Cyprus', @ShortName = N'Cyprus', @Alpha2Code = N'CY';
EXEC AddCountry @FullName = N'Czechia', @ShortName = N'Czechia', @Alpha2Code = N'CZ';
EXEC AddCountry @FullName = N'Denmark', @ShortName = N'Denmark', @Alpha2Code = N'DK';
EXEC AddCountry @FullName = N'Djibouti', @ShortName = N'Djibouti', @Alpha2Code = N'DJ';
EXEC AddCountry @FullName = N'Dominica', @ShortName = N'Dominica', @Alpha2Code = N'DM';
EXEC AddCountry @FullName = N'Dominican Republic', @ShortName = N'Dominican Republic', @Alpha2Code = N'DO';
EXEC AddCountry @FullName = N'Ecuador', @ShortName = N'Ecuador', @Alpha2Code = N'EC';
EXEC AddCountry @FullName = N'Egypt', @ShortName = N'Egypt', @Alpha2Code = N'EG';
EXEC AddCountry @FullName = N'El Salvador', @ShortName = N'El Salvador', @Alpha2Code = N'SV';
EXEC AddCountry @FullName = N'Equatorial Guinea', @ShortName = N'Equatorial Guinea', @Alpha2Code = N'GQ';
EXEC AddCountry @FullName = N'Eritrea', @ShortName = N'Eritrea', @Alpha2Code = N'ER';
EXEC AddCountry @FullName = N'Estonia', @ShortName = N'Estonia', @Alpha2Code = N'EE';
EXEC AddCountry @FullName = N'Eswatini', @ShortName = N'Eswatini', @Alpha2Code = N'SZ';
EXEC AddCountry @FullName = N'Ethiopia', @ShortName = N'Ethiopia', @Alpha2Code = N'ET';
EXEC AddCountry @FullName = N'Faroe Islands', @ShortName = N'Faroe Islands', @Alpha2Code = N'FO';
EXEC AddCountry @FullName = N'Fiji', @ShortName = N'Fiji', @Alpha2Code = N'FJ';
EXEC AddCountry @FullName = N'Finland', @ShortName = N'Finland', @Alpha2Code = N'FI';
EXEC AddCountry @FullName = N'France', @ShortName = N'France', @Alpha2Code = N'FR';
EXEC AddCountry @FullName = N'French Polynesia', @ShortName = N'French Polynesia', @Alpha2Code = N'PF';
EXEC AddCountry @FullName = N'Gabon', @ShortName = N'Gabon', @Alpha2Code = N'GA';
EXEC AddCountry @FullName = N'Gambia', @ShortName = N'Gambia', @Alpha2Code = N'GM';
EXEC AddCountry @FullName = N'Georgia', @ShortName = N'Georgia', @Alpha2Code = N'GE';
EXEC AddCountry @FullName = N'Germany', @ShortName = N'Germany', @Alpha2Code = N'DE';
EXEC AddCountry @FullName = N'Ghana', @ShortName = N'Ghana', @Alpha2Code = N'GH';
EXEC AddCountry @FullName = N'Gibraltar', @ShortName = N'Gibraltar', @Alpha2Code = N'GI';
EXEC AddCountry @FullName = N'Great Britain', @ShortName = N'Great Britain', @Alpha2Code = N'GB';
EXEC AddCountry @FullName = N'Greece', @ShortName = N'Greece', @Alpha2Code = N'GR';
EXEC AddCountry @FullName = N'Greenland', @ShortName = N'Greenland', @Alpha2Code = N'GL';
EXEC AddCountry @FullName = N'Grenada', @ShortName = N'Grenada', @Alpha2Code = N'GD';
EXEC AddCountry @FullName = N'Guam', @ShortName = N'Guam', @Alpha2Code = N'GU';
EXEC AddCountry @FullName = N'Guatemala', @ShortName = N'Guatemala', @Alpha2Code = N'GT';
EXEC AddCountry @FullName = N'Guinea', @ShortName = N'Guinea', @Alpha2Code = N'GN';
EXEC AddCountry @FullName = N'Guinea-Bissau', @ShortName = N'Guinea-Bissau', @Alpha2Code = N'GW';
EXEC AddCountry @FullName = N'Guyana', @ShortName = N'Guyana', @Alpha2Code = N'GY';
EXEC AddCountry @FullName = N'Haiti', @ShortName = N'Haiti', @Alpha2Code = N'HT';
EXEC AddCountry @FullName = N'Honduras', @ShortName = N'Honduras', @Alpha2Code = N'HN';
EXEC AddCountry @FullName = N'Hong Kong', @ShortName = N'Hong Kong', @Alpha2Code = N'HK';
EXEC AddCountry @FullName = N'Hungary', @ShortName = N'Hungary', @Alpha2Code = N'HU';
EXEC AddCountry @FullName = N'Iceland', @ShortName = N'Iceland', @Alpha2Code = N'IS';
EXEC AddCountry @FullName = N'India', @ShortName = N'India', @Alpha2Code = N'IN';
EXEC AddCountry @FullName = N'Indonesia', @ShortName = N'Indonesia', @Alpha2Code = N'ID';
EXEC AddCountry @FullName = N'Iran', @ShortName = N'Iran', @Alpha2Code = N'IR';
EXEC AddCountry @FullName = N'Iraq', @ShortName = N'Iraq', @Alpha2Code = N'IQ';
EXEC AddCountry @FullName = N'Ireland', @ShortName = N'Ireland', @Alpha2Code = N'IE';
EXEC AddCountry @FullName = N'Isle of Man', @ShortName = N'Isle of Man', @Alpha2Code = N'IM';
EXEC AddCountry @FullName = N'Israel', @ShortName = N'Israel', @Alpha2Code = N'IL';
EXEC AddCountry @FullName = N'Italy', @ShortName = N'Italy', @Alpha2Code = N'IT';
EXEC AddCountry @FullName = N'Jamaica', @ShortName = N'Jamaica', @Alpha2Code = N'JM';
EXEC AddCountry @FullName = N'Japan', @ShortName = N'Japan', @Alpha2Code = N'JP';
EXEC AddCountry @FullName = N'Jordan', @ShortName = N'Jordan', @Alpha2Code = N'JO';
EXEC AddCountry @FullName = N'Kazakhstan', @ShortName = N'Kazakhstan', @Alpha2Code = N'KZ';
EXEC AddCountry @FullName = N'Kenya', @ShortName = N'Kenya', @Alpha2Code = N'KE';
EXEC AddCountry @FullName = N'Kiribati', @ShortName = N'Kiribati', @Alpha2Code = N'KI';
EXEC AddCountry @FullName = N'North Korea', @ShortName = N'North Korea', @Alpha2Code = N'KP';
EXEC AddCountry @FullName = N'South Korea', @ShortName = N'South Korea', @Alpha2Code = N'KR';
EXEC AddCountry @FullName = N'Kosovo', @ShortName = N'Kosovo', @Alpha2Code = N'XK';
EXEC AddCountry @FullName = N'Kuwait', @ShortName = N'Kuwait', @Alpha2Code = N'KW';
EXEC AddCountry @FullName = N'Kyrgyz Republic', @ShortName = N'Kyrgyz Republic', @Alpha2Code = N'KG';
EXEC AddCountry @FullName = N'Lao PDR', @ShortName = N'Lao PDR', @Alpha2Code = N'LA';
EXEC AddCountry @FullName = N'Latvia', @ShortName = N'Latvia', @Alpha2Code = N'LV';
EXEC AddCountry @FullName = N'Lebanon', @ShortName = N'Lebanon', @Alpha2Code = N'LB';
EXEC AddCountry @FullName = N'Lesotho', @ShortName = N'Lesotho', @Alpha2Code = N'LS';
EXEC AddCountry @FullName = N'Liberia', @ShortName = N'Liberia', @Alpha2Code = N'LR';
EXEC AddCountry @FullName = N'Libya', @ShortName = N'Libya', @Alpha2Code = N'LY';
EXEC AddCountry @FullName = N'Liechtenstein', @ShortName = N'Liechtenstein', @Alpha2Code = N'LI';
EXEC AddCountry @FullName = N'Lithuania', @ShortName = N'Lithuania', @Alpha2Code = N'LT';
EXEC AddCountry @FullName = N'Luxembourg', @ShortName = N'Luxembourg', @Alpha2Code = N'LU';
EXEC AddCountry @FullName = N'Macao', @ShortName = N'Macao', @Alpha2Code = N'MO';
EXEC AddCountry @FullName = N'Madagascar', @ShortName = N'Madagascar', @Alpha2Code = N'MG';
EXEC AddCountry @FullName = N'Malawi', @ShortName = N'Malawi', @Alpha2Code = N'MW';
EXEC AddCountry @FullName = N'Malaysia', @ShortName = N'Malaysia', @Alpha2Code = N'MY';
EXEC AddCountry @FullName = N'Maldives', @ShortName = N'Maldives', @Alpha2Code = N'MV';
EXEC AddCountry @FullName = N'Mali', @ShortName = N'Mali', @Alpha2Code = N'ML';
EXEC AddCountry @FullName = N'Malta', @ShortName = N'Malta', @Alpha2Code = N'MT';
EXEC AddCountry @FullName = N'Marshall Islands', @ShortName = N'Marshall Islands', @Alpha2Code = N'MH';
EXEC AddCountry @FullName = N'Mauritania', @ShortName = N'Mauritania', @Alpha2Code = N'MR';
EXEC AddCountry @FullName = N'Mauritius', @ShortName = N'Mauritius', @Alpha2Code = N'MU';
EXEC AddCountry @FullName = N'Mexico', @ShortName = N'Mexico', @Alpha2Code = N'MX';
EXEC AddCountry @FullName = N'Micronesia', @ShortName = N'Micronesia', @Alpha2Code = N'FM';
EXEC AddCountry @FullName = N'Moldova', @ShortName = N'Moldova', @Alpha2Code = N'MD';
EXEC AddCountry @FullName = N'Monaco', @ShortName = N'Monaco', @Alpha2Code = N'MC';
EXEC AddCountry @FullName = N'Mongolia', @ShortName = N'Mongolia', @Alpha2Code = N'MN';
EXEC AddCountry @FullName = N'Montenegro', @ShortName = N'Montenegro', @Alpha2Code = N'ME';
EXEC AddCountry @FullName = N'Morocco', @ShortName = N'Morocco', @Alpha2Code = N'MA';
EXEC AddCountry @FullName = N'Mozambique', @ShortName = N'Mozambique', @Alpha2Code = N'MZ';
EXEC AddCountry @FullName = N'Myanmar', @ShortName = N'Myanmar', @Alpha2Code = N'MM';
EXEC AddCountry @FullName = N'Namibia', @ShortName = N'Namibia', @Alpha2Code = N'NA';
EXEC AddCountry @FullName = N'Nauru', @ShortName = N'Nauru', @Alpha2Code = N'NR';
EXEC AddCountry @FullName = N'Nepal', @ShortName = N'Nepal', @Alpha2Code = N'NP';
EXEC AddCountry @FullName = N'Netherlands', @ShortName = N'Netherlands', @Alpha2Code = N'NL';
EXEC AddCountry @FullName = N'New Caledonia', @ShortName = N'New Caledonia', @Alpha2Code = N'NC';
EXEC AddCountry @FullName = N'New Zealand', @ShortName = N'New Zealand', @Alpha2Code = N'NZ';
EXEC AddCountry @FullName = N'Nicaragua', @ShortName = N'Nicaragua', @Alpha2Code = N'NI';
EXEC AddCountry @FullName = N'Niger', @ShortName = N'Niger', @Alpha2Code = N'NE';
EXEC AddCountry @FullName = N'Nigeria', @ShortName = N'Nigeria', @Alpha2Code = N'NG';
EXEC AddCountry @FullName = N'North Macedonia', @ShortName = N'North Macedonia', @Alpha2Code = N'MK';
EXEC AddCountry @FullName = N'Northern Mariana Islands', @ShortName = N'Northern Mariana Islands', @Alpha2Code = N'MP';
EXEC AddCountry @FullName = N'Norway', @ShortName = N'Norway', @Alpha2Code = N'NO';
EXEC AddCountry @FullName = N'Oman', @ShortName = N'Oman', @Alpha2Code = N'OM';
EXEC AddCountry @FullName = N'Pakistan', @ShortName = N'Pakistan', @Alpha2Code = N'PK';
EXEC AddCountry @FullName = N'Palau', @ShortName = N'Palau', @Alpha2Code = N'PW';
EXEC AddCountry @FullName = N'Panama', @ShortName = N'Panama', @Alpha2Code = N'PA';
EXEC AddCountry @FullName = N'Papua New Guinea', @ShortName = N'Papua New Guinea', @Alpha2Code = N'PG';
EXEC AddCountry @FullName = N'Paraguay', @ShortName = N'Paraguay', @Alpha2Code = N'PY';
EXEC AddCountry @FullName = N'Peru', @ShortName = N'Peru', @Alpha2Code = N'PE';
EXEC AddCountry @FullName = N'Philippines', @ShortName = N'Philippines', @Alpha2Code = N'PH';
EXEC AddCountry @FullName = N'Poland', @ShortName = N'Poland', @Alpha2Code = N'PL';
EXEC AddCountry @FullName = N'Portugal', @ShortName = N'Portugal', @Alpha2Code = N'PT';
EXEC AddCountry @FullName = N'Puerto Rico', @ShortName = N'Puerto Rico', @Alpha2Code = N'PR';
EXEC AddCountry @FullName = N'Qatar', @ShortName = N'Qatar', @Alpha2Code = N'QA';
EXEC AddCountry @FullName = N'Romania', @ShortName = N'Romania', @Alpha2Code = N'RO';
EXEC AddCountry @FullName = N'Russian Federation', @ShortName = N'Russia', @Alpha2Code = N'RU';
EXEC AddCountry @FullName = N'Rwanda', @ShortName = N'Rwanda', @Alpha2Code = N'RW';
EXEC AddCountry @FullName = N'Samoa', @ShortName = N'Samoa', @Alpha2Code = N'WS';
EXEC AddCountry @FullName = N'San Marino', @ShortName = N'San Marino', @Alpha2Code = N'SM';
EXEC AddCountry @FullName = N'Sao Tome and Principe', @ShortName = N'Sao Tome and Principe', @Alpha2Code = N'ST';
EXEC AddCountry @FullName = N'Saudi Arabia', @ShortName = N'Saudi Arabia', @Alpha2Code = N'SA';
EXEC AddCountry @FullName = N'Senegal', @ShortName = N'Senegal', @Alpha2Code = N'SN';
EXEC AddCountry @FullName = N'Serbia', @ShortName = N'Serbia', @Alpha2Code = N'RS';
EXEC AddCountry @FullName = N'Seychelles', @ShortName = N'Seychelles', @Alpha2Code = N'SC';
EXEC AddCountry @FullName = N'Sierra Leone', @ShortName = N'Sierra Leone', @Alpha2Code = N'SL';
EXEC AddCountry @FullName = N'Singapore', @ShortName = N'Singapore', @Alpha2Code = N'SG';
EXEC AddCountry @FullName = N'Sint Maarten', @ShortName = N'Sint Maarten', @Alpha2Code = N'SX';
EXEC AddCountry @FullName = N'Slovak Republic', @ShortName = N'Slovak Republic', @Alpha2Code = N'SK';
EXEC AddCountry @FullName = N'Slovenia', @ShortName = N'Slovenia', @Alpha2Code = N'SI';
EXEC AddCountry @FullName = N'Solomon Islands', @ShortName = N'Solomon Islands', @Alpha2Code = N'SB';
EXEC AddCountry @FullName = N'Somalia', @ShortName = N'Somalia', @Alpha2Code = N'SO';
EXEC AddCountry @FullName = N'South Africa', @ShortName = N'South Africa', @Alpha2Code = N'ZA';
EXEC AddCountry @FullName = N'South Sudan', @ShortName = N'South Sudan', @Alpha2Code = N'SS';
EXEC AddCountry @FullName = N'Spain', @ShortName = N'Spain', @Alpha2Code = N'ES';
EXEC AddCountry @FullName = N'Sri Lanka', @ShortName = N'Sri Lanka', @Alpha2Code = N'LK';
EXEC AddCountry @FullName = N'St. Kitts and Nevis', @ShortName = N'St. Kitts and Nevis', @Alpha2Code = N'KN';
EXEC AddCountry @FullName = N'St. Lucia', @ShortName = N'St. Lucia', @Alpha2Code = N'LC';
EXEC AddCountry @FullName = N'St. Martin', @ShortName = N'St. Martin', @Alpha2Code = N'MF';
EXEC AddCountry @FullName = N'St. Vincent and the Grenadines', @ShortName = N'St. Vincent and the Grenadines', @Alpha2Code = N'VC';
EXEC AddCountry @FullName = N'Sudan', @ShortName = N'Sudan', @Alpha2Code = N'SD';
EXEC AddCountry @FullName = N'Suriname', @ShortName = N'Suriname', @Alpha2Code = N'SR';
EXEC AddCountry @FullName = N'Sweden', @ShortName = N'Sweden', @Alpha2Code = N'SE';
EXEC AddCountry @FullName = N'Switzerland', @ShortName = N'Switzerland', @Alpha2Code = N'CH';
EXEC AddCountry @FullName = N'Syrian Arab Republic', @ShortName = N'Syrian Arab Republic', @Alpha2Code = N'SY';
EXEC AddCountry @FullName = N'Tajikistan', @ShortName = N'Tajikistan', @Alpha2Code = N'TJ';
EXEC AddCountry @FullName = N'Tanzania', @ShortName = N'Tanzania', @Alpha2Code = N'TZ';
EXEC AddCountry @FullName = N'Thailand', @ShortName = N'Thailand', @Alpha2Code = N'TH';
EXEC AddCountry @FullName = N'Timor-Leste', @ShortName = N'Timor-Leste', @Alpha2Code = N'TL';
EXEC AddCountry @FullName = N'Togo', @ShortName = N'Togo', @Alpha2Code = N'TG';
EXEC AddCountry @FullName = N'Tonga', @ShortName = N'Tonga', @Alpha2Code = N'TO';
EXEC AddCountry @FullName = N'Trinidad and Tobago', @ShortName = N'Trinidad and Tobago', @Alpha2Code = N'TT';
EXEC AddCountry @FullName = N'Tunisia', @ShortName = N'Tunisia', @Alpha2Code = N'TN';
EXEC AddCountry @FullName = N'Turkey', @ShortName = N'Turkey', @Alpha2Code = N'TR';
EXEC AddCountry @FullName = N'Turkmenistan', @ShortName = N'Turkmenistan', @Alpha2Code = N'TM';
EXEC AddCountry @FullName = N'Turks and Caicos Islands', @ShortName = N'Turks and Caicos Islands', @Alpha2Code = N'TC';
EXEC AddCountry @FullName = N'Tuvalu', @ShortName = N'Tuvalu', @Alpha2Code = N'TV';
EXEC AddCountry @FullName = N'Uganda', @ShortName = N'Uganda', @Alpha2Code = N'UG';
EXEC AddCountry @FullName = N'Ukraine', @ShortName = N'Ukraine', @Alpha2Code = N'UA';
EXEC AddCountry @FullName = N'United Arab Emirates', @ShortName = N'U.A.E.', @Alpha2Code = N'AE';
EXEC AddCountry @FullName = N'United States', @ShortName = N'USA', @Alpha2Code = N'US';
EXEC AddCountry @FullName = N'Uruguay', @ShortName = N'Uruguay', @Alpha2Code = N'UY';
EXEC AddCountry @FullName = N'Uzbekistan', @ShortName = N'Uzbekistan', @Alpha2Code = N'UZ';
EXEC AddCountry @FullName = N'Vanuatu', @ShortName = N'Vanuatu', @Alpha2Code = N'VU';
EXEC AddCountry @FullName = N'Venezuela', @ShortName = N'Venezuela', @Alpha2Code = N'VE';
EXEC AddCountry @FullName = N'Vietnam', @ShortName = N'Vietnam', @Alpha2Code = N'VN';
EXEC AddCountry @FullName = N'Virgin Islands', @ShortName = N'Virgin Islands', @Alpha2Code = N'VI';
EXEC AddCountry @FullName = N'West Bank and Gaza', @ShortName = N'West Bank and Gaza', @Alpha2Code = N'GZ';
EXEC AddCountry @FullName = N'Yemen', @ShortName = N'Yemen', @Alpha2Code = N'YE';
EXEC AddCountry @FullName = N'Zambia', @ShortName = N'Zambia', @Alpha2Code = N'ZM';
EXEC AddCountry @FullName = N'Zimbabwe', @ShortName = N'Zimbabwe', @Alpha2Code = N'ZW';